// LP テンプレート設定
// 新しい職種LPを追加する場合はここにエントリを追加するだけ

export const LP_TEMPLATES = [
  {
    id: "fitness",
    label: "フィットネス・ヨガ",
    emoji: "💪",
    path: "/lp/fitness",
    color: "#F5A623",
    revenueRate: 85,
    freeMonths: 12,
    slots: 50,
    heroTitle: "Private Fitness\nRevolution",
    heroSub: "次世代パーソナル指導プラットフォーム：Chat Market始動",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 先着50名限定",
    published: true,
  },
  {
    id: "expert",
    label: "有識者・講演",
    emoji: "👑",
    path: "/lp/expert",
    color: "#3B82F6",
    revenueRate: 85,
    freeMonths: 12,
    slots: null,
    heroTitle: "知の価値を、\n最大限に売ろう",
    heroSub: "3,000名規模の講演会・セミナーで圧倒的な収益を実現",
    ctaBadge: "還元率 85% | 初期費用0円 | 24時間サポート",
    published: true,
  },
  {
    id: "fortune",
    label: "占い師",
    emoji: "🔮",
    path: "/fortune-lp",
    color: "#8B5CF6",
    revenueRate: 85,
    freeMonths: 12,
    slots: null,
    heroTitle: "占い師として\n稼ぐ時代へ",
    heroSub: "あなたの鑑定力を、最高のプラットフォームで収益化",
    ctaBadge: "還元率 85% | 初期費用0円",
    published: true,
  },
  {
    id: "musician",
    label: "ミュージシャン",
    emoji: "🎸",
    path: "/musician",
    color: "#EC4899",
    revenueRate: 85,
    freeMonths: 12,
    slots: null,
    heroTitle: "あなたの音を\n最高にカッコよく売ろう",
    heroSub: "事務所いらず、初期費用ゼロ",
    ctaBadge: "還元率 85% | 初期費用0円",
    published: true,
  },
  {
    id: "idol",
    label: "アイドル・タレント",
    emoji: "⭐",
    path: "/idol-lp",
    color: "#F472B6",
    revenueRate: 85,
    freeMonths: 12,
    slots: null,
    heroTitle: "あなたの輝きを\n収益に変えよう",
    heroSub: "事務所いらず、初期費用ゼロ",
    ctaBadge: "還元率 85% | 初期費用0円",
    published: true,
  },
  {
    id: "tutor",
    label: "家庭教師・教育",
    emoji: "📚",
    path: "/lp/tutor",
    color: "#3B82F6",
    revenueRate: 90,
    freeMonths: 12,
    slots: 100,
    heroTitle: "THE HOME TEACHER",
    heroSub: "教育者の価値を最大化する次世代プラットフォーム",
    ctaBadge: "還元率 90% | 12ヶ月無料 | 先着100名",
    published: true,
  },
  // ── 未公開テンプレート（画像・文言差替で即公開可能）──
  {
    id: "career",
    label: "キャリアコンサルタント・人事",
    emoji: "🧭",
    path: "/lp/career",
    color: "#1B2B6B",
    revenueRate: 85,
    freeMonths: 12,
    slots: 50,
    heroTitle: "Career Navigation\nProject",
    heroSub: "1対1模擬面接×メンタルケア：専門家のための新聖域",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 秘密厳守",
    published: true,
  },
  {
    id: "lawyer",
    label: "士業（弁護士・税理士）",
    emoji: "⚖️",
    path: "/lp/lawyer",
    color: "#1B2B6B",
    revenueRate: 85,
    freeMonths: 12,
    slots: 30,
    heroTitle: "士業の価値を\nオンラインで解放",
    heroSub: "弁護士・税理士・司法書士のための次世代相談プラットフォーム",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 先着30名限定",
    published: false,
  },
  {
    id: "cooking",
    label: "料理・フード",
    emoji: "🍳",
    path: "/lp/cooking",
    color: "#F97316",
    revenueRate: 85,
    freeMonths: 12,
    slots: 50,
    heroTitle: "あなたのレシピを\n収益に変えよう",
    heroSub: "プロシェフ・料理研究家のための収益化プラットフォーム",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 先着50名限定",
    published: false,
  },
  {
    id: "pet",
    label: "ペット・動物",
    emoji: "🐾",
    path: "/lp/pet",
    color: "#F59E0B",
    revenueRate: 85,
    freeMonths: 12,
    slots: 50,
    heroTitle: "ペット専門家の\n価値を届けよう",
    heroSub: "トレーナー・獣医・ペットシッターのための収益化プラットフォーム",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 先着50名限定",
    published: false,
  },
  {
    id: "beauty",
    label: "美容・メイク",
    emoji: "💄",
    path: "/lp/beauty",
    color: "#F43F5E",
    revenueRate: 85,
    freeMonths: 12,
    slots: 50,
    heroTitle: "あなたの美を\nオンラインで届けよう",
    heroSub: "美容師・メイクアップアーティストのための収益化プラットフォーム",
    ctaBadge: "還元率 85% | 12ヶ月無料 | 先着50名限定",
    published: false,
  },
];

export function getTemplateById(id) {
  return LP_TEMPLATES.find((t) => t.id === id);
}

export const PUBLISHED_TEMPLATES = LP_TEMPLATES.filter((t) => t.published);
export const DRAFT_TEMPLATES = LP_TEMPLATES.filter((t) => !t.published);